### ISSUE TITLE
GitHub integration

### ISSUE THREAD

**Issue by a17** [stabilitydao/app#2]
**Problem**
App does not provide organization open-source development activity and its contributors data.

**Solution**
Use github organization data through github api.

**Alternatives**
There are probably enough alternative solutions, but the proposed solution seens as the most native and promising.

**More**
[Github REST API](https://docs.github.com/en/rest)

**Comment by Ed17K** [comment]
There is a reason why people keep certain codes closed. Cause its secret recipe for our own good. You don't want people to copy and go out there just duplicating our work and change UI and become theirs. Plus opensource also means invitation to hackers to inject stuffs

**Comment by a17** [comment]
> There is a reason why people keep certain codes closed. Cause its secret recipe for our own good. You don't want people to copy and go out there just duplicating our work and change UI and become theirs. Plus opensource also means invitation to hackers to inject stuffs

To do open source you need to be confident and strong enough in spirit. Not everyone is capable of this. :smile:

**Comment by Ed17K** [comment]
yes we can. But its also like open a restaurant. They have their secret recipe and at the same time serve other common food to others.
